
using System.Linq;
using System.Text;
using Content.Client._EE.UserInterface.Controls.CodeEdit;
using Content.Shared._EE.Iterasm;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Span = System.Range;

namespace Content.Client._EE.Iterasm;

[GenerateTypedNameReferences]
public sealed partial class IterasmDbgUiFragment : BoxContainer
{
    public IterasmDbgUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        SourceInput.Formatter = new Formatter(SourceInput);
    }

    private sealed class Formatter(CodeEdit codeEdit) : CodeEdit.ICodeEditFormatter
    {
        private readonly List<Span> _comments = new();

        private static Robust.Client.ResourceManagement.IResourceCache Cache => IoCManager.Resolve<Robust.Client.ResourceManagement.IResourceCache>();
        private static readonly Robust.Client.Graphics.VectorFont ItalicFont
            = new(Cache.GetResource<Robust.Client.ResourceManagement.FontResource>("/Fonts/RobotoMono/RobotoMono-Italic.ttf"), 12);

        public void ResetCache()
        {
            _comments.Clear();

            int? commentStart = null;

            var i = 0;
            foreach (var leaf in Rope.CollectLeaves(codeEdit.TextRope))
            {
                foreach (var c in leaf.Text)
                {
                    if (c == ';' && commentStart is not null)
                        commentStart = i;
                    else if (c == '\n' && commentStart is { } start)
                    {
                        _comments.Add(new Span(start, i - start));
                        commentStart = null;
                    }

                    i++;
                }
            }
        }

        public CodeEdit.ICodeEditFormatter.TextFormattingDelegate GetFormatCallback(int charIdx, CodeEdit.CodeEditFormatState state)
        {
            if (_comments.TakeWhile(span => span.Start.Value < charIdx).Any(span => span.End.Value > charIdx))
            {
                state.TextColor = Color.Green;
                state.OverrideFont = ItalicFont;
            }

            return Callback;
        }

        private void Callback(int charIdx, CodeEdit.CodeEditFormatState state)
        {
            switch (Rope.Index(codeEdit.TextRope, charIdx))
            {
                case ';':
                    state.TextColor = Color.Green;
                    state.OverrideFont = ItalicFont;
                    break;
                case '\n':
                    state.TextColor = null;
                    state.OverrideFont = null;
                    break;
                default:
                    break;
            }
        }
    }

    public void UpdateState(IterasmDbgUiState state)
    {
        // Check if state is IterasmDbgUiCompErrorState or IterasmDbgUiOkState
        switch (state)
        {
            case IterasmDbgUiCompErrorState compErrState:
                MetaInfo.Text = $"[font size=8]{compErrState.ErrorMessage}[/font]";
                LineCol.Text = $"[font size=8]Ln {compErrState.Line + 1}[/font]";
                break;

            default:
                break;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var cursorPos = (uint) SourceInput.CursorPosition.Index;

        var (lineIdx, lineStart, _) = GetLineColInfo(SourceInput.TextRope, cursorPos);
        var col = cursorPos - lineStart;

        LineCol.Text = $"[font size=8]Ln {lineIdx + 1}, Col {col + 1}[/font]";
    }

    private static (uint lineIdx, uint lineStart, uint lineEnd) GetLineColInfo(Rope.Node rope, uint charPos)
    {
        var lineIdx = 0u;
        var lineStart = 0u;
        var charIdx = 0u;

        using var runes = Rope.EnumerateRunes(rope).GetEnumerator();

        // Determine how many lines down we are.
        while (runes.MoveNext())
        {
            var rune = runes.Current;

            if (charIdx == charPos)
                break;

            if (rune == new Rune('\n'))
            {
                lineIdx++;
                lineStart = charIdx + 1;
            }

            charIdx += (uint) rune.Utf16SequenceLength;
        }

        // Means the cursor is positioned at the end of the rope.
        // That's all the information we actually need.
        if (charIdx < charPos)
            return (lineIdx, lineStart, charIdx);

        // Find the end of the line.
        while (runes.Current != new Rune('\n'))
        {
            if (!runes.MoveNext())
            {
                // We reached the end of the rope without finding a newline.
                // The end of the line is the end of the rope.
                return (lineIdx, lineStart, charIdx);
            }

            charIdx += (uint) runes.Current.Utf16SequenceLength;
        }

        return (lineIdx, lineStart, charIdx);
    }
}
