
using Content.Client._EE.UserInterface.Controls.CodeEdit;
using Content.Shared._EE.Iterasm;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._EE.Iterasm;

[GenerateTypedNameReferences]
public sealed partial class IterasmDbgUiFragment : BoxContainer
{
    public IterasmDbgUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        SourceInput.Formatter = new Formatter(SourceInput);
    }

    private sealed class Formatter(CodeEdit codeEdit) : CodeEdit.ICodeEditFormatter
    {
        private static Robust.Client.ResourceManagement.IResourceCache Cache => IoCManager.Resolve<Robust.Client.ResourceManagement.IResourceCache>();
        private static readonly Robust.Client.Graphics.VectorFont ItalicFont
            = new(Cache.GetResource<Robust.Client.ResourceManagement.FontResource>("/Fonts/RobotoMono/RobotoMono-Italic.ttf"), 12);
        private static readonly Robust.Client.Graphics.VectorFont BoldFont
            = new(Cache.GetResource<Robust.Client.ResourceManagement.FontResource>("/Fonts/RobotoMono/RobotoMono-Bold.ttf"), 12);

        private readonly List<bool> _lineBreaks = new();

        public void ClearCache()
        {
            _lineBreaks.Clear();
            try
            {
                var i = 0;
                while (true)
                {
                    _lineBreaks.Add(Rope.Index(codeEdit.TextRope, i) == '\n');
                    i++;
                }

            }
            catch (IndexOutOfRangeException)
            { }
        }

        public CodeEdit.ICodeEditFormatter.TextFormattingDelegate GetFormatCallback(int charIdx, CodeEdit.CodeEditFormatState state)
        {
            var lineCount = 0;
            foreach (var nl in _lineBreaks[..charIdx])
            {
                if (nl) lineCount++;
            }

            return (idx, fmtState) => Callback(ref lineCount, codeEdit.TextRope, idx, fmtState);
        }

        private static void Callback(ref int lineCount, Rope.Node text, int charIdx, CodeEdit.CodeEditFormatState state)
        {
            if (Rope.Index(text, charIdx) == '\n')
                lineCount++;

            if (lineCount % 3 == 0)
                state.Underline = new(Color.Red);
            else
                state.Underline = null;
        }
    }

    public void UpdateState(IterasmDbgUiState state)
    {
        // Check if state is IterasmDbgUiCompErrorState or IterasmDbgUiOkState
        switch (state)
        {
            case IterasmDbgUiCompErrorState compErrState:
                MetaInfo.Text = $"[font size=8]{compErrState.ErrorMessage}[/font]";
                LineCol.Text = $"[font size=8]Ln {compErrState.Line + 1}[/font]";
                break;

            default:
                break;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var cursorPos = (uint) SourceInput.CursorPosition.Index;

        var (lineIdx, lineStart, _) = GetLineColInfo(SourceInput.TextRope, cursorPos);
        var col = cursorPos - lineStart;

        LineCol.Text = $"[font size=8]Ln {lineIdx + 1}, Col {col + 1}[/font]";
    }

    private static (uint lineIdx, uint lineStart, uint lineEnd) GetLineColInfo(Rope.Node rope, uint pos)
    {
        var lineIdx = 0u;
        var lineStart = 0u;
        var charIdx = 0u;

        try
        {
            while (charIdx < pos)
            {
                if (Rope.Index(rope, charIdx) == '\n')
                {
                    lineIdx++;
                    lineStart = charIdx + 1;
                }

                charIdx++;
            }
        }
        catch (IndexOutOfRangeException)
        {
            // Means the cursor is positioned at the end of the rope.
            // That's all the information we actually need.
            return (lineIdx, lineStart, charIdx);
        }

        // Find the end of the line.
        try
        {
            while (Rope.Index(rope, charIdx) != '\n')
                charIdx++;
        }
        catch (IndexOutOfRangeException)
        {
            // We overran, so the end of the line is one char back.
            charIdx--;
        }

        return (lineIdx, lineStart, charIdx);
    }
}
