
using Content.Shared._EE.Iterasm;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._EE.Iterasm;

[GenerateTypedNameReferences]
public sealed partial class IterasmDbgUiFragment : BoxContainer
{

    public event Action<string>? OnNoteAdded;
    public event Action<string>? OnNoteRemoved;

    public IterasmDbgUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;
    }

    public void UpdateState(IterasmDbgUiState state)
    {
        // Check if state is IterasmDbgUiCompErrorState or IterasmDbgUiOkState
        switch (state)
        {
            case IterasmDbgUiCompErrorState compErrState:
                MetaInfo.Text = $"[font size=8]{compErrState.ErrorMessage}[/font]";
                LineCol.Text = $"[font size=8]Ln {compErrState.Line + 1}[/font]";
                break;

            default:
                break;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var cursorPos = (uint) SourceInput.CursorPosition.Index;

        var (lineIdx, lineStart, _) = GetLineColInfo(SourceInput.TextRope, cursorPos);
        var col = cursorPos - lineStart;

        LineCol.Text = $"[font size=8]Ln {lineIdx + 1}, Col {col + 1}[/font]";
    }

    private static (uint lineIdx, uint lineStart, uint lineEnd) GetLineColInfo(Rope.Node rope, uint pos)
    {
        var lineIdx = 0u;
        var lineStart = 0u;
        var charIdx = 0u;

        try
        {
            while (charIdx < pos)
            {
                if (Rope.Index(rope, charIdx) == '\n')
                {
                    lineIdx++;
                    lineStart = charIdx + 1;
                }

                charIdx++;
            }
        }
        catch (IndexOutOfRangeException)
        {
            // Means the cursor is positioned at the end of the rope.
            // That's all the information we actually need.
            return (lineIdx, lineStart, charIdx);
        }

        // Find the end of the line.
        try
        {
            while (Rope.Index(rope, charIdx) != '\n')
                charIdx++;
        }
        catch (IndexOutOfRangeException)
        {
            // We overran, so the end of the line is one char back.
            charIdx--;
        }

        return (lineIdx, lineStart, charIdx);
    }

    private void AddNote(string note)
    {
        var row = new BoxContainer();
        row.HorizontalExpand = true;
        row.Orientation = LayoutOrientation.Horizontal;
        row.Margin = new Thickness(4);

        var label = new Label();
        label.Text = note;
        label.HorizontalExpand = true;
        label.ClipText = true;

        var removeButton = new TextureButton();
        removeButton.AddStyleClass("windowCloseButton");
        removeButton.OnPressed += _ => OnNoteRemoved?.Invoke(label.Text);

        row.AddChild(label);
        row.AddChild(removeButton);

        // MessageContainer.AddChild(row);
    }
}
